version: 2

models:
  - name: dim_instrument
    description: |
      Instrument dimension (SCD Type 1 - current state only).
      
      We use SCD-1 here because:
      - Millions of instruments across asset classes
      - Frequent minor attribute updates on OTC instruments
      - SCD-2 would multiply storage significantly
      - Most analytics need current attributes
    columns:
      - name: instrument_id
        description: Unique instrument identifier
        tests:
          - unique
          - not_null
      - name: symbol
        description: Trading symbol
      - name: isin
        description: ISIN code (may be null for OTC instruments)
      - name: asset_class
        description: Asset class (e.g., EQUITY, FX, RATES)
        tests:
          - accepted_values:
              values: ['EQUITY', 'FX', 'RATES', 'CREDIT', 'COMMODITIES', 'OTHER']
              config:
                severity: warn
      - name: currency
        description: Primary currency
        tests:
          - not_null
