#markets:
#  target: int
#  outputs:
#    int:
#      type: bigquery
#      method: oauth  # Uses application default credentials in GKE
#      project: markets-int-12345
#      dataset: staging  # Default dataset, overridden per model
#      location: europe-west2
#      threads: 4
#      timeout_seconds: 300
#      priority: interactive
#      retries: 1
#
#    prod:
#      type: bigquery
#      method: oauth
#      project: markets-prod-12345
#      dataset: staging
#      location: europe-west2
#      threads: 4
#      timeout_seconds: 300
#      priority: interactive
#      retries: 1
#
#    # CI target for compilation checks (no credentials needed)
#    ci:
#      type: bigquery
#      method: oauth
#      project: markets-ci-mock
#      dataset: staging
#      location: europe-west2
#      threads: 1
#      timeout_seconds: 60
#      # This target is only used for `dbt compile` in CI
#      # It will fail if you try to run models against it
markets:
  target: local
  outputs:
    local:
      type: duckdb
      path: ./markets.duckdb        # Local file; can be anywhere you want
      schema: staging               # Mirrors your BigQuery dataset name
      threads: 4

    int:
      type: bigquery
      method: oauth
      project: markets-int-12345
      dataset: staging
      location: europe-west2
      threads: 4
      timeout_seconds: 300
      priority: interactive
      retries: 1

    prod:
      type: bigquery
      method: oauth
      project: markets-prod-12345
      dataset: staging
      location: europe-west2
      threads: 4
      timeout_seconds: 300
      priority: interactive
      retries: 1

    ci:
      type: bigquery
      method: oauth
      project: markets-ci-mock
      dataset: staging
      location: europe-west2
      threads: 1
      timeout_seconds: 60
