version: 2

sources:
  - name: raw
    description: Raw data loaded from CSV files
    schema: "{% if target.type == 'duckdb' %}main{% else %}{{ var('raw_dataset', 'surveillance_raw') }}{% endif %}"
    database: "{% if target.type == 'bigquery' %}{{ var('project_id', '') }}{% endif %}"
    
    tables:
      - name: raw_futures_order_events
        description: |
          Raw futures order events loaded from CSV.
          One row per event (fill, amend, cancel etc).
          All columns are strings for flexibility.
        columns:
          - name: ExtractDate
            description: Date the data was extracted
          - name: OrderMessageID
            description: Unique order identifier
          - name: EventSeq
            description: Event sequence number within order
          - name: _load_id
            description: Load batch identifier for lineage
        
      - name: load_metadata
        description: |
          Tracks every file load.
          Used for lineage and incremental processing.
        columns:
          - name: load_id
            description: Unique load identifier
          - name: filename
            description: Source filename
          - name: row_count
            description: Number of rows loaded
