# dbt profiles for surveillance pipeline
# 
# Local development: dbt run --target dev
# Production:        dbt run --target prod
#
# For local dev, this file can live in the project directory.
# For prod, use environment variables or ~/.dbt/profiles.yml
#
# Note: The default path '../dev.duckdb' is relative to this dbt directory,
# pointing to the same database the orchestrator writes to in the parent folder.
# The orchestrator clears DUCKDB_PATH when invoking dbt to ensure this default is used.

surveillance:
  target: dev

  outputs:
    # Local development with DuckDB
    dev:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH', '../dev.duckdb') }}"
      threads: 4

    # Production with BigQuery
    prod:
      type: bigquery
      method: oauth  # or service_account
      project: "{{ env_var('GCP_PROJECT') }}"
      dataset: "{{ env_var('BQ_DATASET', 'surveillance') }}"
      threads: 8
      timeout_seconds: 300
      location: "{{ env_var('BQ_LOCATION', 'EU') }}"
      priority: interactive
      retries: 3