project_id                   = "markets-int-12345"
region                       = "europe-west2"
zone                         = "europe-west2-a"
kafka_brokers                = "kafka-int.internal:9092"
regulator_api_url            = "https://api.regulator-uat.example.com/v1/submit"
