name: surveillance
version: '1.0.0'

# Don't treat warnings as errors
flags:
  warn_error: false

# Store test failures in tables for analysis
tests:
  +store_failures: true
  +severity: warn  # Default tests to warn, not error

# Configure on-run-end for logging
on-run-end:
  - "{{ log_run_results() }}"